# Generated by Django 3.1.7 on 2021-09-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre2', models.CharField(max_length=30)),
                ('tipo2', models.CharField(max_length=15)),
                ('operacion2', models.CharField(max_length=15)),
                ('superficie2', models.IntegerField()),
                ('habitaciones2', models.IntegerField()),
                ('banno2', models.IntegerField()),
                ('ubicacion2', models.TextField()),
                ('precio2', models.IntegerField()),
                ('descripcion2', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
